language: python
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 3.5

addons:
    apt:
        sources:
        - r-packages-precise
        packages:
        - r-base-dev

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda/bin:$PATH
    - export PATH=$HOME/miniconda2/bin:$PATH
    - hash -r
    - conda update --yes conda
    # are not specific to using mini
    # - sudo rm -rf /dev/shm
    # - sudo ln -s /run/shm /dev/shm
    # This help testing code with pylab
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in test.synapseConfig.enc -out test.synapseConfig -d; mv test.synapseConfig ~/.synapseConfig; fi'



install:
  # sometimes cython compilation of the cython files takes forever
  # here we install cython with specific options
  # https://miail.python.org/pipermail/cython-devel/2014-November/004263.html
  #- pip install --install-option="--no-cython-compile" cython --upgrade
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose pandas coverage scikit-learn numexpr xlrd cython
  # coverage packages are elsewhere
  #- conda install --yes -c python-coveralls nose-cov
  - pip install nose easydev --upgrade
  - pip install synapseclient
  - pip install coveralls -v
  - pip install biokit fitter -v 
  - pip install tabulate -v
  - pip install git+https://git@github.com/cokelaer/synapsePythonClient.git@v1.4.0_py3_dreamtools#egg=synapsePythonClient -v

# # command to run tests, e.g. python setup.py test
script:
  - python setup.py nosetests --with-coverage --cover-package dreamtools

after_success:
  coveralls
